# Generated by Django 4.0.2 on 2022-05-08 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='userPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='socialApp.profile'),
        ),
    ]
