# Generated by Django 4.0.2 on 2022-05-08 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0003_alter_group_owner_alter_group_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='userComment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='socialApp.profile'),
        ),
    ]
