# Generated by Django 4.0.2 on 2022-05-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0004_alter_comment_usercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
