# Generated by Django 4.0.2 on 2022-05-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0005_alter_profile_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
