# Generated by Django 4.0.2 on 2022-05-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0006_alter_post_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imageUrl',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='imageUrl',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
